//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by speak.RC
//
#define ICON_APP                        10
#define DLG_ABOUT                       100
#define IDD_ABOUT_VERSION_OS            101
#define IDD_TYPING                      101
#define IDD_ABOUT_VERSION_PLATFORM      102
#define IDD_ABOUT_REG_INSTALLER         103
#define IDD_ABOUT_REG_COMPANY           104
#define IDD_ABOUT_DECTALK_VERSION       105
#define IDD_ABOUT_DECTALK_VERSION_STR   106
#define IDB_BITMAP_SKIN                 107
#define IDB_BITMAP_PLAY                 108
#define IDB_BITMAP_PAUSE                109
#define IDB_BITMAP_STOP                 110
#define IDB_BITMAP_PLAYDN               112
#define IDB_BITMAP_PAUSEDN              113
#define IDB_BITMAP_STOPDN               114
#define IDD_DIALOG_PARAMETERS           115
#define VS_PerfectPaul                  1000
#define VS_BeautifulBetty               1001
#define VS_HugeHarry                    1002
#define IDC_BITMAPAREA                  1003
#define VS_FrailFrank                   1003
#define VS_DoctorDenis                  1004
#define VS_KitTheKid                    1005
#define VS_UpittyUrsula                 1006
#define VS_RoughRita                    1007
#define VS_WisperingWendy               1008
#define VS_US_Paul                      1009
#define VS_US_Betty                     1010
#define VS_US_Harry                     1011
#define VS_US_Frank                     1012
#define VS_US_Dennis                    1013
#define VS_US_Kit                       1014
#define VS_US_Ursula                    1015
#define VS_US_Rita                      1016
#define VS_US_Wendy                     1017
#define VS_SP_Paul                      1018
#define VS_SP_Betty                     1019
#define VS_SP_Harry                     1020
#define VS_SP_Frank                     1021
#define VS_SP_Dennis                    1022
#define VS_SP_Kit                       1023
#define VS_SP_Ursula                    1024
#define VS_SP_Rita                      1025
#define VS_SP_Wendy                     1026
#define VS_LA_Paul                      1027
#define VS_LA_Betty                     1028
#define VS_LA_Harry                     1029
#define VS_LA_Frank                     1030
#define VS_LA_Dennis                    1031
#define VS_LA_Kit                       1032
#define VS_LA_Ursula                    1033
#define VS_LA_Rita                      1034
#define VS_LA_Wendy                     1035
#define VS_GR_Paul                      1036
#define VS_GR_Betty                     1037
#define VS_GR_Harry                     1038
#define VS_GR_Frank                     1039
#define VS_GR_Dennis                    1040
#define VS_GR_Kit                       1041
#define VS_GR_Ursula                    1042
#define VS_GR_Rita                      1043
#define VS_GR_Wendy                     1044
#define VS_FR_Paul                      1045
#define VS_FR_Betty                     1046
#define VS_FR_Harry                     1047
#define VS_FR_Frank                     1048
#define VS_FR_Dennis                    1049
#define VS_FR_Kit                       1050
#define VS_FR_Ursula                    1051
#define VS_FR_Rita                      1052
#define VS_FR_Wendy                     1053
#define VS_IT_Paul                      1054
#define VS_IT_Betty                     1055
#define VS_IT_Harry                     1056
#define VS_IT_Frank                     1057
#define VS_IT_Dennis                    1058
#define VS_IT_Kit                       1059
#define VS_IT_Ursula                    1060
#define VS_IT_Rita                      1061
#define VS_IT_Wendy                     1062
#define TS_PerfectPaul                  1100
#define TS_BeautifulBetty               1101
#define TS_HugeHarry                    1102
#define TS_FrailFrank                   1103
#define TS_DoctorDenis                  1104
#define TS_KitTheKid                    1105
#define TS_UpittyUrsula                 1106
#define TS_RoughRita                    1107
#define TS_WisperingWendy               1108
#define VS_CH_Paul                      1200
#define VS_CH_Betty                     1201
#define VS_CH_Harry                     1202
#define VS_CH_Frank                     1203
#define VS_CH_Dennis                    1204
#define VS_CH_Kit                       1205
#define VS_CH_Ursula                    1206
#define VS_CH_Rita                      1207
#define VS_CH_Wendy                     1208
#define VS_JP_Paul                      1220
#define VS_JP_Betty                     1221
#define VS_JP_Harry                     1222
#define VS_JP_Frank                     1223
#define VS_JP_Dennis                    1224
#define VS_JP_Kit                       1225
#define VS_JP_Ursula                    1226
#define VS_JP_Rita                      1227
#define VS_JP_Wendy                     1228
#define VS_KR_Paul                      1240
#define VS_KR_Betty                     1241
#define VS_KR_Harry                     1242
#define VS_KR_Frank                     1243
#define VS_KR_Dennis                    1244
#define VS_KR_Kit                       1245
#define VS_KR_Ursula                    1246
#define VS_KR_Rita                      1247
#define VS_KR_Wendy                     1248
#define VS_HB_Paul                      1260
#define VS_HB_Betty                     1261
#define VS_HB_Harry                     1262
#define VS_HB_Frank                     1263
#define VS_HB_Dennis                    1264
#define VS_HB_Kit                       1265
#define VS_HB_Ursula                    1266
#define VS_HB_Rita                      1267
#define VS_HB_Wendy                     1268
#define IDC_SLIDER_RATE                 1300
#define IDC_SLIDER_PITCH                1301
#define IDC_SLIDER_VOLUME               1302
#define IDC_EDIT_PITCH                  1303
#define IDC_EDIT_VOLUME                 1304
#define IDC_EDIT_RATE                   1305
#define IDC_EDIT1                       2000
#define IDM_HELP                        40001
#define IDM_ABOUT                       40002
#define ID_CLOSE                        40003
#define ID_CPANEL                       40004
#define IDM_SHOW_ROMANJI                40005
#define IDM_HIGHLIGHT                   40006
#define IDM_TYPING                      40007
#define IDM_RESTART                     40008
#define IDM_ENGLISH                     40009
#define IDM_FRENCH                      40010
#define IDM_GERMAN                      40011
#define IDM_ITALIAN                     40012
#define IDM_LATIN                       40013
#define IDM_SPANISH                     40014
#define IDM_ENGLISH_UK                  40015
#define IDM_CHINESE                     40016
#define IDM_JAPANESE                    40017
#define IDM_KOREAN                      40018
#define IDM_HEBREW                      40019
#define ID_VOICE_PAUL                   40100
#define ID_VOICE_BETTY                  40101
#define ID_VOICE_HARRY                  40102
#define ID_VOICE_FRANK                  40103
#define ID_VOICE_DENNIS                 40104
#define ID_VOICE_KIT                    40105
#define ID_VOICE_URSULA                 40106
#define ID_VOICE_RITA                   40107
#define ID_VOICE_WENDY                  40108
#define IDM_FILE_NEW                    40200
#define IDM_FILE_OPEN                   40201
#define IDM_SAVE                        40202
#define IDM_SAVEAS                      40203
#define IDM_FILE_CLOSE                  40204
#define IDM_LOAD_DIC                    40205
#define IDM_UNLOAD_DIC                  40206
#define IDM_WAVE1116                    40207
#define IDM_WAVE1108                    40208
#define IDM_MULAW                       40209
#define IDM_EXIT                        40210
#define ID_EDIT_PARAMETERS              40211
#define ID_EDIT_CLEAR                   0xE120
#define ID_EDIT_CLEAR_ALL               0xE121
#define ID_EDIT_COPY                    0xE122
#define ID_EDIT_CUT                     0xE123
#define ID_EDIT_FIND                    0xE124
#define ID_EDIT_PASTE                   0xE125
#define ID_EDIT_SELECT_ALL              0xE12A
#define ID_EDIT_UNDO                    0xE12B
#define ID_EDIT_REDO                    0xE12C
#define ID_FIND                         0xE12D
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        116
#define _APS_NEXT_COMMAND_VALUE         40212
#define _APS_NEXT_CONTROL_VALUE         1306
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
